package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Light / Day Mode (Blue & Amber)
val LightPrimary = Color(0xFF2563EB)
val LightPrimaryContainer = Color(0xFFDBEAFE)
val LightOnPrimaryContainer = Color(0xFF1E3A8A)
val LightSecondary = Color(0xFFD97706)
val LightSecondaryContainer = Color(0xFFFEF3C7)
val LightOnSecondaryContainer = Color(0xFF78350F)
val LightTertiary = Color(0xFF0D9488)
val LightBackground = Color(0xFFF8FAFC)
val LightSurface = Color(0xFFFFFFFF)
val LightSurfaceVariant = Color(0xFFF1F5F9)
val LightTextPrimary = Color(0xFF0F172A)
val LightTextSecondary = Color(0xFF475569)

// Dark / Night Mode (Slate & Neon highlights)
val DarkPrimary = Color(0xFF93C5FD)
val DarkPrimaryContainer = Color(0xFF1E3A8A)
val DarkOnPrimaryContainer = Color(0xFFDBEAFE)
val DarkSecondary = Color(0xFFFCD34D)
val DarkSecondaryContainer = Color(0xFF78350F)
val DarkOnSecondaryContainer = Color(0xFFFEF3C7)
val DarkTertiary = Color(0xFF5EEAD4)
val DarkBackground = Color(0xFF0F172A)
val DarkSurface = Color(0xFF1E293B)
val DarkSurfaceVariant = Color(0xFF334155)
val DarkTextPrimary = Color(0xFFF8FAFC)
val DarkTextSecondary = Color(0xFF94A3B8)

// Emerald Mode (Nature, Sage & Mint)
val EmeraldPrimary = Color(0xFF059669)
val EmeraldPrimaryContainer = Color(0xFFD1FAE5)
val EmeraldOnPrimaryContainer = Color(0xFF064E3B)
val EmeraldSecondary = Color(0xFF0D9488)
val EmeraldSecondaryContainer = Color(0xFFCCFBF1)
val EmeraldOnSecondaryContainer = Color(0xFF134E4A)
val EmeraldTertiary = Color(0xFF16A34A)
val EmeraldBackground = Color(0xFFF0FDF4)
val EmeraldSurface = Color(0xFFFFFFFF)
val EmeraldSurfaceVariant = Color(0xFFDCFCE7)
val EmeraldTextPrimary = Color(0xFF064E3B)
val EmeraldTextSecondary = Color(0xFF166534)

// Terracotta Mode (Warm Earth, Amber & Sunset)
val TerracottaPrimary = Color(0xFFEA580C)
val TerracottaPrimaryContainer = Color(0xFFFFEDD5)
val TerracottaOnPrimaryContainer = Color(0xFF7C2D12)
val TerracottaSecondary = Color(0xFFD97706)
val TerracottaSecondaryContainer = Color(0xFFFEF3C7)
val TerracottaOnSecondaryContainer = Color(0xFF78350F)
val TerracottaTertiary = Color(0xFFE11D48)
val TerracottaBackground = Color(0xFFFFFBEB)
val TerracottaSurface = Color(0xFFFFFFFF)
val TerracottaSurfaceVariant = Color(0xFFFED7AA)
val TerracottaTextPrimary = Color(0xFF431407)
val TerracottaTextSecondary = Color(0xFF7C2D12)

